export const GET_CURRENT_WEATHER = "GET_CURRENT_WEATHER";
export const GET_CURRENT_WEATHER_SUCCESS = "GET_CURRENT_WEATHER_SUCCESS";
export const GET_CURRENT_WEATHER_ERROR = "GET_CURRENT_WEATHER_ERROR";

export const GET_FORECAST_WEATHER = "GET_FORECAST_WEATHER";
export const GET_FORECAST_WEATHER_SUCCESS = "GET_FORECAST_WEATHER_SUCCESS";
export const GET_FORECAST_WEATHER_ERROR = "GET_FORECAST_WEATHER_ERROR";
